services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "40000-40100:40000-40100/udp"
      - "40000-40100:40000-40100/tcp"
    volumes:
      - ./ssl:/app/ssl
    environment:
      - NODE_ENV=production
      - LISTEN_IP=0.0.0.0
      - ANNOUNCED_IP=4931257-dv98943.twc1.net
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=4931257-dv98943.twc1.net
      - HTTPS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3001"
    volumes:
      - ./ssl:/app/ssl
    environment:
      - NODE_ENV=production
      - HTTPS=true
      - SSL_CRT_FILE=/app/ssl/certificate.crt
      - SSL_KEY_FILE=/app/ssl/private.key
      - REACT_APP_SERVER_URL=https://4931257-dv98943.twc1.net:3000
      - REACT_APP_ICE_SERVERS=[{"urls":["turn:185.119.59.23:3478"],"username":"test","credential":"test123"}]
    networks:
      - app-network
    depends_on:
      - server
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 